admin/src/Settings/AccessTokenList.jsx

Refactored admin/src/settings/AccessTokenList.jsx, converted from class style to function style.

refactored Access Token List

---

admin/src/Components/Login.jsx

Converted React Class Component to a React Functional Component in admin/src/Components/Login.jsx

refactored login class to function

---

admin/src/Components/MessageForm.jsx
admin/src/Components/ProductForm.jsx

Refactor form files (message and product)

---

admin/src/Components/RequestPasswordReset.jsx

request password refactor

---

admin/src/Components/SearchBox.jsx
admin/src/Components/SelectInput.jsx
admin/src/Components/TextInput.jsx
admin/src/Components/Textarea.jsx

**Textarea**
**SelectInput**
**TextInput**
**Searchbox**

Form input components refactored

---

admin/src/Components/CategoryPeriodsInput.js
admin/src/Components/CollectionTable.js
admin/src/Components/CountryDropdown.jsx
admin/src/Components/FileInput.jsx
admin/src/Components/GroupForm.js
admin/src/Components/KeyHandoutForm.jsx

- Refactored from class components to function components
- Process `/bin/sh -c npm run eslint` passes during `make test`
-  admin/src/Components/CategoryPeriodsInput.js:6
-  admin/src/Components/CollectionTable.js:5
-  admin/src/Components/CountryDropdown.jsx:1044
-  admin/src/Components/FileInput.jsx:5
- no other files seem to depend on this file, can't find in UI
-  admin/src/Components/GroupForm.js:7
-  admin/src/Components/KeyHandoutForm.jsx:87

Refactored component files - 2

---

admin/src/Membership/KeyHandout.jsx
admin/src/Membership/MemberBox.jsx
admin/src/Membership/MemberBoxMemberData.jsx

What?
Refactor from class components to function components the following files:
admin/src/Membership/KeyHandout.jsx
admin/src/Membership/MemberBox.jsx
admin/src/Membership/MemberBoxMemberData.jsx
Manual UI Testing
admin/src/Membership/MemberBox.jsx
admin/src/Membership/MemberBoxMemberData.jsx

refactor MemberBox and associated children components

---

admin/src/Membership/KeyEdit.jsx

What:
Refactor class components to function components admin/src/Membership/KeyEdit.jsx
Testing:

refactor KeyEdit

---

admin/src/Membership/MemberBoxPermissions.js

What:
class components to function components admin/src/Membership/MemberBoxPermissions.js
Testing

Refactor MemberBoxPermissions

---

admin/src/Membership/MemberBoxNewMessage.js

What:
Convert class components to function components admin/src/Membership/MemberBoxNewMessage.js
Testing:

refactor Member Box New Message

---

admin/src/Membership/MemberBoxKeys.js

What:
Convert class components to function components admin/src/Membership/MemberBoxKeys.js
Testing:

refactor Member Box Keys

---

admin/src/Membership/MemberAdd.js

What:
Refactored from class components to function components admin/src/Membership/MemberAdd.js
Testing:

refactor admin/src/Membership/MemberAdd.js

---

admin/src/Membership/MemberBoxGroups.js

added import { get } from "../gateway";

fix get error

---

admin/src/Membership/MemberBoxSpans.jsx
admin/src/Membership/MemberExport.jsx
admin/src/Membership/MembershipPeriodsInput.js
admin/src/Membership/SpanShow.jsx

refactored membership

---

admin/src/Messages/MessageAdd.js
admin/src/Messages/MessageShow.js
admin/src/Sales/OrderShow.js

- linter pass
- UI:
- test message "123"

refactored messages

---

admin/src/Sales/AccountingBox.jsx
admin/src/Sales/AccountingProduct.js
admin/src/Sales/GiftCardShow.js

- linter pass
- UI:
- test case: added new cost center

changed sales

---

admin/src/Sales/ProductAdd.js

- linter pass
- UI:
- test case: added product "12345"

changed productadd

---

admin/src/Sales/ProductEdit.jsx

- linter pass
- UI:
- test case: edit basemembership

changed productEdit

---

admin/src/Settings/ServiceTokenList.jsx

changed class to function in servicetokenlist

changed class to function in servicetokenlist

---

admin/src/Membership/MemberBoxSpans.jsx
admin/src/Membership/MembershipPeriodsInput.js

The member spans page works now: http://localhost:8009/membership/members/1/spans

fix span error

---

admin/src/Sales/GiftCardShow.js

Fix gift-card page render issue: causes infinite network requests.

fix gift card network error

---

admin/src/Messages/MessageAdd.js
admin/src/Messages/MessageShow.js

The email log page is fixed: http://localhost:8009/messages/1
new message test:

fix messages
